## data manipulation using pandas

In [1]:
import pandas as pd

In [2]:
car_sales =pd.read_csv("data/1 car-sales.csv")

In [3]:
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [4]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [5]:
car_sales["Make"] = car_sales["Make"].str.lower()

In [6]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  toyota  White         150043      4   $4,000.00
1   honda    Red          87899      4   $5,000.00
2  toyota   Blue          32549      3   $7,000.00
3     bmw  Black          11179      5  $22,000.00
4  nissan  White         213095      4   $3,500.00
5  toyota  Green          99213      4   $4,500.00
6   honda   Blue          45698      4   $7,500.00
7   honda   Blue          54738      4   $7,000.00
8  toyota  White          60000      4   $6,250.00
9  nissan  White          31600      4   $9,700.00

In [7]:
car_sales.columns =car_sales.columns.str.lower() #cange column names to lowercase

In [8]:
car_sales

     make colour  odometer (km)  doors       price
0  toyota  White         150043      4   $4,000.00
1   honda    Red          87899      4   $5,000.00
2  toyota   Blue          32549      3   $7,000.00
3     bmw  Black          11179      5  $22,000.00
4  nissan  White         213095      4   $3,500.00
5  toyota  Green          99213      4   $4,500.00
6   honda   Blue          45698      4   $7,500.00
7   honda   Blue          54738      4   $7,000.00
8  toyota  White          60000      4   $6,250.00
9  nissan  White          31600      4   $9,700.00

In [9]:
str_cols = car_sales.select_dtypes(include=['object']).columns
car_sales[str_cols] = car_sales[str_cols].apply(lambda x: x.str.lower()) #change all object entries to lowercase format

In [10]:
car_sales

     make colour  odometer (km)  doors       price
0  toyota  white         150043      4   $4,000.00
1   honda    red          87899      4   $5,000.00
2  toyota   blue          32549      3   $7,000.00
3     bmw  black          11179      5  $22,000.00
4  nissan  white         213095      4   $3,500.00
5  toyota  green          99213      4   $4,500.00
6   honda   blue          45698      4   $7,500.00
7   honda   blue          54738      4   $7,000.00
8  toyota  white          60000      4   $6,250.00
9  nissan  white          31600      4   $9,700.00

In [11]:
car_sales.price = car_sales.price.replace('[\$\.\,]', '', regex= True).astype('float64')
car_sales.price = car_sales.price/100

In [12]:
car_sales

     make colour  odometer (km)  doors    price
0  toyota  white         150043      4   4000.0
1   honda    red          87899      4   5000.0
2  toyota   blue          32549      3   7000.0
3     bmw  black          11179      5  22000.0
4  nissan  white         213095      4   3500.0
5  toyota  green          99213      4   4500.0
6   honda   blue          45698      4   7500.0
7   honda   blue          54738      4   7000.0
8  toyota  white          60000      4   6250.0
9  nissan  white          31600      4   9700.0

In [13]:
car_sales.to_csv("data/initialManipulation.csv")

## missing values handling
we now have an dataframe with missing values included. This is how the real world operates and we will see the ways we could handle the missing values

In [28]:
car_sales_missing  = pd.read_csv("data/initialManipulation.csv")

In [29]:
car_sales_missing

   Unnamed: 0    make colour  odometer (km)  doors    price
0           0  toyota  white       150043.0      4   4000.0
1           1   honda    red        87899.0      4   5000.0
2           2  toyota    NaN        32549.0      3   7000.0
3           3     bmw  black        11179.0      5  22000.0
4           4  nissan  white       213095.0      4   3500.0
5           5  toyota  green        99213.0      4   4500.0
6           6   honda   blue            NaN      4   7500.0
7           7   honda   blue        54738.0      4   7000.0
8           8  toyota  white        60000.0      4   6250.0
9           9  nissan  white        31600.0      4   9700.0

#### fillna 
this is used to fill the missing values with statistical estimate to continue using the data. For numerical data, we could use the mean or median, or maybe 
quadrant values too, for categorical values we could use modes to replace the missing values.

In [30]:
car_sales_missing =car_sales_missing.drop(columns= "Unnamed: 0", axis=1)

In [31]:
car_sales_missing

     make colour  odometer (km)  doors    price
0  toyota  white       150043.0      4   4000.0
1   honda    red        87899.0      4   5000.0
2  toyota    NaN        32549.0      3   7000.0
3     bmw  black        11179.0      5  22000.0
4  nissan  white       213095.0      4   3500.0
5  toyota  green        99213.0      4   4500.0
6   honda   blue            NaN      4   7500.0
7   honda   blue        54738.0      4   7000.0
8  toyota  white        60000.0      4   6250.0
9  nissan  white        31600.0      4   9700.0

In [32]:
car_sales_missing["odometer (km)"].fillna(car_sales_missing['odometer (km)'].mean(), inplace=True)

/tmp/ipykernel_328865/2315632221.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_sales_missing["odometer (km)"].fillna(car_sales_missing['odometer (km)'].mean(), inplace=True)

In [33]:
car_sales_missing

     make colour  odometer (km)  doors    price
0  toyota  white  150043.000000      4   4000.0
1   honda    red   87899.000000      4   5000.0
2  toyota    NaN   32549.000000      3   7000.0
3     bmw  black   11179.000000      5  22000.0
4  nissan  white  213095.000000      4   3500.0
5  toyota  green   99213.000000      4   4500.0
6   honda   blue   82257.333333      4   7500.0
7   honda   blue   54738.000000      4   7000.0
8  toyota  white   60000.000000      4   6250.0
9  nissan  white   31600.000000      4   9700.0

In [38]:
#replace the categorical NaN with a mode value
car_sales_missing.colour.fillna(car_sales_missing['colour'].mode()[0], inplace=True)

key note on how **mode** works
mode works in a manner a bit different from the numerical center of tendency measures. the mode() function returns al lisst of values and
fillna doesnt know what to do with it, so it does nothing. we have to tell the fillna function to take the first index (0) in order to get the one with the highest value.

In [39]:
car_sales_missing

     make colour  odometer (km)  doors    price
0  toyota  white  150043.000000      4   4000.0
1   honda    red   87899.000000      4   5000.0
2  toyota  white   32549.000000      3   7000.0
3     bmw  black   11179.000000      5  22000.0
4  nissan  white  213095.000000      4   3500.0
5  toyota  green   99213.000000      4   4500.0
6   honda   blue   82257.333333      4   7500.0
7   honda   blue   54738.000000      4   7000.0
8  toyota  white   60000.000000      4   6250.0
9  nissan  white   31600.000000      4   9700.0

### dropna function
unlike fillna function, dropna is used to drop entries that have a NaN value in them. This method is efficient if too many attributes of a tuple are missing and it is disadvantageous to have the tuple compared to the risk and misiformation it could bring.

In [42]:
car_sales_missing =pd.read_csv("data/initialManipulation.csv")

In [45]:
car_sales_missing.dropna(inplace=True)

In [46]:
car_sales_missing.drop("Unnamed: 0", axis =1)

     make colour  odometer (km)  doors    price
0  toyota  white       150043.0      4   4000.0
1   honda    red        87899.0      4   5000.0
3     bmw  black        11179.0      5  22000.0
4  nissan  white       213095.0      4   3500.0
7   honda   blue        54738.0      4   7000.0
8  toyota  white        60000.0      4   6250.0
9  nissan  white        31600.0      4   9700.0

we can see using the indexes that rows(entries) with missing entries(NaN ) are removed from the dataframe. we can now save the cleaned data in another csv

In [47]:
car_sales_missing.to_csv("data/car_sales_missing_handled.csv")